### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on master

### ISSUE THREAD

**Issue by saikpr** [mholt/timeliner#43] opened 2019-06-17 16:20 UTC
➜ ./timeliner add-account google_photos/sainyam.kapoor.cse12@itbhu.ac.in
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7439b0]

goroutine 1 [running]:
github.com/mholt/timeliner.authorizeWithOAuth2(0x9d6631, 0x6, 0xe35f60, 0x1, 0x1, 0x7405bc, 0x80, 0x95bb40, 0x4000126f28, 0x7405f8)
	/home/sainyam/go/src/github.com/mholt/timeliner/oauth2.go:57 +0x50
github.com/mholt/timeliner.DataSource.authFunc.func1(0x7fdc21d5fa, 0x20, 0x9d8bab, 0xd, 0x9d6631, 0x6, 0xe35f60)
	/home/sainyam/go/src/github.com/mholt/timeliner/datasource.go:116 +0x68
github.com/mholt/timeliner.(*Timeline).Authenticate(0x400000f0a0, 0x7fdc21d5ec, 0xd, 0x7fdc21d5fa, 0x20, 0x0, 0x400000f0c0)
	/home/sainyam/go/src/github.com/mholt/timeliner/account.go:79 +0x4a8
github.com/mholt/timeliner.(*Timeline).AddAccount(0x400000f0a0, 0x7fdc21d5ec, 0xd, 0x7fdc21d5fa, 0x20, 0x1, 0x0)
	/home/sainyam/go/src/github.com/mholt/timeliner/account.go:63 +0x2f0
main.main()
	/home/sainyam/go/src/github.com/mholt/timeliner/cmd/timeliner/main.go:91 +0x48c

This is happening at the first stage,

**Comment by mholt** [comment] 2019-06-17 17:38
You are probably missing a (proper) configuration file... probably a duplicate of https://github.com/mholt/timeliner/issues/7 <--- should help!

**Closed as completed by mholt** 2019-06-17 17:38 UTC
Labels: bug, duplicate
